import React, { useState, useEffect, useCallback, useRef } from "react";
import { X, Zap, Clock, Ban, AlertCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

export interface ColumnMeta {
    column_name: string;
    data_type: string;
    is_nullable: string;
    column_default: string | null;
    is_identity: string;
}

function isAutoGenerated(col: ColumnMeta): boolean {
    if (col.is_identity === 'YES') return true;
    const def = (col.column_default ?? '').toLowerCase();
    return (
        def.includes('nextval(') ||
        def.includes('gen_random_uuid()') ||
        def.includes('uuid_generate_v4()') ||
        def.includes('uuid_generate_v1()')
    );
}

function isTimestamp(col: ColumnMeta): boolean {
    return col.data_type.includes('timestamp') || col.data_type === 'date';
}

function hasDbDefault(col: ColumnMeta): boolean {
    return col.is_identity === 'YES' || (col.column_default !== null && col.column_default !== '');
}

function isRequired(col: ColumnMeta): boolean {
    return col.is_nullable === 'NO' && !hasDbDefault(col) && !isAutoGenerated(col);
}

/** Returns datetime-local string for "now" */
function nowLocal(): string {
    const now = new Date();
    now.setSeconds(0, 0);
    return now.toISOString().slice(0, 16);
}

function inferInputType(col: ColumnMeta): string {
    const dt = col.data_type;
    if (dt.includes('int') || dt === 'numeric' || dt === 'real' || dt === 'double precision' || dt === 'decimal') return 'number';
    if (dt.includes('timestamp')) return 'timestamp';
    if (dt === 'date') return 'date';
    if (dt === 'boolean') return 'bool';
    if (dt === 'json' || dt === 'jsonb') return 'json';
    return 'text';
}

const inputCls = cn(
    "w-full bg-background border border-border rounded-md px-3 py-2",
    "text-sm text-foreground placeholder:text-muted-foreground/40",
    "outline-none hover:border-muted-foreground/40",
    "focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-colors"
);

function NullToggle({ isNull, onToggle }: { isNull: boolean; onToggle: () => void }) {
    return (
        <button
            type="button"
            onClick={onToggle}
            title={isNull ? "Click to enter a value" : "Click to set NULL"}
            className={cn(
                "flex items-center gap-1 text-[10px] font-mono px-2 py-0.5 rounded border transition-all",
                isNull
                    ? "bg-amber-500/15 border-amber-500/40 text-amber-400"
                    : "bg-muted/40 border-border text-muted-foreground/50 hover:border-muted-foreground/30 hover:text-muted-foreground"
            )}
        >
            <Ban className="w-2.5 h-2.5" />
            NULL
        </button>
    );
}

function ColumnField({
    col, value, isNull, onToggleNull, onChange, hasError,
}: {
    col: ColumnMeta;
    value: any;
    isNull: boolean;
    onToggleNull: () => void;
    onChange: (v: any) => void;
    hasError?: boolean;
}) {
    const autoGen = isAutoGenerated(col);
    const ts = isTimestamp(col);
    const inputType = inferInputType(col);
    const dbDefault = col.column_default;
    const nullable = col.is_nullable === 'YES';
    const required = isRequired(col);

    return (
        <div className="space-y-1.5">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-1.5">
                    <label className={cn("text-xs font-medium", hasError ? "text-red-500" : "text-foreground/80")}>
                        {col.column_name}
                    </label>
                    {required && (
                        <span className="text-[9px] font-bold text-red-400 uppercase tracking-wider">required</span>
                    )}
                </div>
                <div className="flex items-center gap-2">
                    <span className="text-[10px] font-mono text-muted-foreground/60 bg-muted/40 px-1.5 py-0.5 rounded">
                        {col.data_type}
                    </span>
                    {!autoGen && (
                        <NullToggle isNull={isNull} onToggle={onToggleNull} />
                    )}
                </div>
            </div>

            {isNull ? (
                <div className="flex items-center gap-2 px-3 py-2 rounded-md border border-amber-500/30 bg-amber-500/5 text-amber-400/70 text-xs font-mono">
                    <Ban className="w-3 h-3 shrink-0" />
                    NULL — no value will be stored
                </div>
            ) : autoGen ? (
                <div className={cn(
                    "flex items-center gap-2 px-3 py-2 rounded-md border border-border bg-muted/20",
                    "text-sm text-muted-foreground/60"
                )}>
                    <Zap className="w-3.5 h-3.5 text-primary shrink-0" />
                    <span className="text-xs">Auto-generated by database</span>
                </div>
            ) : hasError ? (
                <div className="flex items-center gap-2 px-3 py-2 rounded-md border border-red-500/40 bg-red-500/5 text-red-400 text-xs">
                    <AlertCircle className="w-3.5 h-3.5 shrink-0" />
                    This field is required — please enter a value
                </div>
            ) : inputType === 'timestamp' ? (
                <div className="space-y-1">
                    <input
                        type="datetime-local"
                        value={value || ""}
                        onChange={e => onChange(e.target.value || null)}
                        className={inputCls}
                    />
                    <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground/60">
                        <Clock className="w-3 h-3 shrink-0" />
                        <span>{nullable ? "Leave blank to store NULL" : dbDefault ? `Default: ${dbDefault}` : "Required"}</span>
                    </div>
                </div>
            ) : inputType === 'date' ? (
                <input
                    type="date"
                    value={value || ""}
                    onChange={e => onChange(e.target.value || null)}
                    className={inputCls}
                />
            ) : inputType === 'bool' ? (
                <div className="flex items-center gap-3">
                    {["true", "false"].map(opt => (
                        <label key={opt} className="flex items-center gap-1.5 cursor-pointer">
                            <input
                                type="radio"
                                name={col.column_name}
                                value={opt}
                                checked={value === opt}
                                onChange={() => onChange(opt)}
                                className="accent-primary"
                            />
                            <span className="text-xs text-muted-foreground font-mono">{opt}</span>
                        </label>
                    ))}
                </div>
            ) : inputType === 'number' ? (
                <input
                    type="number"
                    value={value ?? ""}
                    onChange={e => onChange(e.target.value === "" ? null : e.target.value)}
                    placeholder={dbDefault ? `default: ${dbDefault}` : required ? "Required" : "NULL"}
                    className={cn(inputCls, hasError && "border-red-500/50 focus:border-red-500/70 focus:ring-red-500/20")}
                />
            ) : inputType === 'json' ? (
                <textarea
                    value={value || ""}
                    onChange={e => onChange(e.target.value || null)}
                    rows={3}
                    placeholder='{"key": "value"}'
                    className={cn(inputCls, "resize-y font-mono text-xs")}
                />
            ) : (
                <input
                    type="text"
                    value={value || ""}
                    onChange={e => onChange(e.target.value)}
                    placeholder={dbDefault ? `default: ${dbDefault}` : required ? "Required" : `Enter ${col.column_name}…`}
                    className={cn(inputCls, hasError && "border-red-500/50 focus:border-red-500/70 focus:ring-red-500/20")}
                />
            )}
        </div>
    );
}

interface InsertRowPanelProps {
    open: boolean;
    onClose: () => void;
    onSave: (row: Record<string, any>) => void;
    tableName: string;
    columns: ColumnMeta[];
}

export function InsertRowPanel({ open, onClose, onSave, tableName, columns }: InsertRowPanelProps) {
    const [visible, setVisible] = useState(false);
    const [values, setValues] = useState<Record<string, any>>({});
    const [nullFields, setNullFields] = useState<Set<string>>(new Set());
    const [errorFields, setErrorFields] = useState<Set<string>>(new Set());
    const prefillDoneRef = useRef(false);

    useEffect(() => {
        if (open) { requestAnimationFrame(() => setVisible(true)); }
        else { setVisible(false); prefillDoneRef.current = false; }
    }, [open]);

    useEffect(() => {
        if (!open || prefillDoneRef.current || columns.length === 0) return;
        prefillDoneRef.current = true;
        const prefilled: Record<string, any> = {};
        for (const col of columns) {
            if (isAutoGenerated(col)) continue;
            if (isTimestamp(col) && !hasDbDefault(col)) {
                const n = col.column_name.toLowerCase();
                if (n === 'created_at' || n === 'updated_at' || n.endsWith('_at') || n.endsWith('_date')) {
                    prefilled[col.column_name] = nowLocal();
                }
            }
        }
        setValues(prefilled);
        setNullFields(new Set());
        setErrorFields(new Set());
    }, [open, columns]);

    const handleClose = () => {
        setVisible(false);
        setTimeout(() => { setValues({}); setNullFields(new Set()); setErrorFields(new Set()); onClose(); }, 300);
    };

    const handleSave = useCallback(() => {
        const row: Record<string, any> = {};
        const errors = new Set<string>();

        for (const col of columns) {
            if (isAutoGenerated(col)) continue;
            const key = col.column_name;
            if (nullFields.has(key)) {
                row[key] = null;
                continue;
            }
            const v = values[key];
            const blank = v === "" || v === undefined || v === null;
            if (blank && isRequired(col)) {
                errors.add(key);
                continue;
            }
            row[key] = blank ? null : v;
        }

        if (errors.size > 0) {
            setErrorFields(errors);
            const names = [...errors].join(", ");
            toast.error(`Required field${errors.size > 1 ? 's' : ''} missing: ${names}. This column is NOT NULL and has no auto-generate default — please enter a value.`);
            return;
        }

        setErrorFields(new Set());
        onSave(row);
        handleClose();
    }, [values, nullFields, columns]);

    useEffect(() => {
        if (!open) return;
        const handler = (e: KeyboardEvent) => {
            if ((e.ctrlKey || e.metaKey) && e.key === "Enter") handleSave();
            if (e.key === "Escape") handleClose();
        };
        document.addEventListener("keydown", handler);
        return () => document.removeEventListener("keydown", handler);
    }, [open, handleSave]);

    const setField = (col: string, val: any) => {
        setValues(prev => ({ ...prev, [col]: val }));
        setErrorFields(prev => { const next = new Set(prev); next.delete(col); return next; });
    };
    const toggleNull = (col: string) => setNullFields(prev => {
        const next = new Set(prev);
        if (next.has(col)) { next.delete(col); }
        else { next.add(col); setValues(v => ({ ...v, [col]: undefined })); }
        return next;
    });

    if (!open) return null;

    return (
        <>
            <div
                onClick={handleClose}
                className={cn(
                    "fixed inset-0 z-40 bg-black/50 transition-opacity duration-300",
                    visible ? "opacity-100" : "opacity-0"
                )}
            />

            <div className={cn(
                "fixed top-0 right-0 z-50 h-full w-full max-w-[520px] flex flex-col",
                "bg-background border-l border-border shadow-2xl",
                "transition-transform duration-300 ease-out",
                visible ? "translate-x-0" : "translate-x-full"
            )}>
                <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-muted/20 shrink-0">
                    <div>
                        <p className="text-[10px] text-muted-foreground font-mono uppercase tracking-widest mb-0.5">
                            {tableName}
                        </p>
                        <h2 className="text-[15px] font-medium text-foreground">Add new row</h2>
                    </div>
                    <button onClick={handleClose} className="p-1.5 rounded hover:bg-muted text-muted-foreground hover:text-foreground transition-colors">
                        <X className="w-4 h-4" />
                    </button>
                </div>

                <div className="flex-1 overflow-y-auto scrollbar-thin px-6 py-5 space-y-5">
                    {columns.map(col => (
                        <ColumnField
                            key={col.column_name}
                            col={col}
                            value={values[col.column_name]}
                            isNull={nullFields.has(col.column_name)}
                            onToggleNull={() => toggleNull(col.column_name)}
                            onChange={val => setField(col.column_name, val)}
                            hasError={errorFields.has(col.column_name)}
                        />
                    ))}
                </div>

                <div className="flex items-center justify-between px-6 py-4 border-t border-border bg-muted/20 shrink-0">
                    <button
                        onClick={handleClose}
                        className="px-5 py-2 rounded-full text-sm text-foreground border border-border hover:bg-muted transition-all"
                    >
                        Cancel
                    </button>
                    <div className="flex items-center gap-3">
                        <span className="text-[10px] text-muted-foreground/50 font-mono hidden sm:flex items-center gap-1">
                            <kbd className="bg-muted border border-border rounded px-1.5 py-0.5 text-[10px]">Ctrl</kbd>
                            <kbd className="bg-muted border border-border rounded px-1.5 py-0.5 text-[10px]">↵</kbd>
                        </span>
                        <button
                            onClick={handleSave}
                            className="px-6 py-2 rounded-full text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 transition-all shadow-[0_0_16px_rgba(62,207,142,0.2)]"
                        >
                            Save
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
}
